- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: add alacritty repository
    ansible.builtin.apt_repository:
      repo: 'ppa:aslatter/ppa'
      codename: trusty

  - name: install basic packages
    package:
      name:
        - build-essential
        - zsh
        - stow
        - fzf
        - pip
        - alacritty
        - tmux
        - htop
