- hosts: localhost
  connection: local

  tasks:
  - name: add alacritty repository
    apt_repository:
      repo: 'ppa:aslatter/ppa'

  - name: install basic packages
    package:
      name:
        - git
        - build-essential
        - zsh
        - stow
        - fzf
        - pip
        - alacritty
        - tmux
        - htop

  - name: get Hack Nerd Font
    get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: /tmp
      timeout: 60

  - name: create directory to unzip
    file:
      path: ~/.local/share/fonts/NerdFonts
      state: directory

  - name: unzip Hack Nerd Font
    unarchive:
      src: /tmp/Hack.zip
      dest: ~/.local/share/fonts/NerdFonts
      copy: no

  - name: remove temporary Hack.zip file
    file:
      path: /tmp/Hack.zip
      state: absent

  - name: set dynamic workspaces to false
    community.generate.dconf:
      key: "/org/gnome/mutter/dynamic-workspaces"
      value: false

  - name: set number of workspaces
    community.generate.dconf:
      key: "/org/gnome/desktop/wm/preferences/num-workspaces"
      value: 8

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-1"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-2"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-3"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-4"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-5"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-6"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-7"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-8"
      value: []

  - name: remove keybinding for switching app
    community.generate.dconf:
      key: "/org/gnome/shell/keybindings/switch-to-application-9"
      value: []

