- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
  - name: add alacritty repository
    apt_repository:
      repo: 'ppa:aslatter/ppa'
      codename: trusty

  - name: install basic packages
    package:
      name:
        - git
        - build-essential
        - zsh
        - stow
        - fzf
        - pip
        - alacritty
        - tmux
        - htop
